### ISSUE TITLE
Translate the HTML pages

### ISSUE THREAD

**Issue by Situphen** [Alex-D/cookies-cnil-banner#2]
All the code and the README are in English but the HTML pages `en-savoir-plus.html` and `index.html` are in French. It wouldn't be better to translate it in English?

**Comment by Alex-D** [comment]
Nope because CNIL is only in France and the class can be used by any organisation which have french trafic.

**Comment by Situphen** [comment]
But these HTML pages are only here to test the script, no? I mean the developers won't use these HTML pages.

**Comment by Alex-D** [comment]
Some of dev juste copy/paste the demo, so I prefer to keep the code like that.
