### ISSUE TITLE
Allow to pass parameters to the constructor

### ISSUE THREAD

**Issue by Situphen** [Alex-D/cookies-cnil-banner#3]
Actually, the code is unyielding. We can't change the IDs of the buttons and the link, or change the duration of the cookie. I think it would be better if we can pass an object to the constructor like :

````js
var parameters = {
    "too": bar,
};

var cookiesBanner = new CookiesCnilBanner(analyticFunction, parameters);
````

**Comment by Alex-D** [comment]
> We can't change the IDs of the buttons and the link

It's a choice.

> or change the duration of the cookie

Maximum is 13 month defined by CNIL, i put this to it maximum.
